<?php  
$lang = [
  //donate
  
    'home' => 'Home',
    'volunteer' => 'Volunteer',
    'resource_collection' => 'Resource Collection',
    'contact' => 'Contact',
    'donate_funds' => 'Donate Funds',
    'full_name' => 'Full Name',
    'required' => '(required)',
    'email_address' => 'Email Address',
    'donation_amount' => 'Donation Amount',
    'message_optional' => 'Message (optional)',
    'donate_now' => 'Donate Now',
    'recent_donations' => 'Recent Donations',
    'no_donations_yet' => 'No donations yet.',
    'thank_you' => 'Thank you, %s, for your donation!',
    'name_required' => 'Name is required.',
    'valid_email_required' => 'A valid email is required.',
    'valid_amount_required' => 'A valid donation amount is required.',
    'site_title' => 'Relief Sphere',
    'footer_title' => 'About Us',
    'footer_description' => 'Our platform helps report, track, and respond to disaster incidents in real time, promoting rapid action and recovery with community involvement.',
    'copyright' => '© 2025 Relief Sphere. All rights reserved.',
    'about' => 'About',

  // Registration
  'create_account' => 'Create Account',
  'full_name' => 'Full Name',
  'email' => 'Email',
  'password' => 'Password',
  'confirm_password' => 'Confirm Password',
  'phone' => 'Phone Number',
  'register' => 'Register',
  'already_have_account' => 'Already have an account?',
  'login_here' => 'Login here',
  'all_fields_required' => 'All fields are required.',
  'invalid_email' => 'Invalid email format.',
  'passwords_not_match' => 'Passwords do not match.',
  'email_exists' => 'Email already exists.',
  'account_created' => 'Account created successfully',
  'error_try_again' => 'Error occurred. Try again.',
  'admin_email_restricted' => 'You cannot register with this email.',

  //up reg
  'create_account' => 'Create Account',
    'full_name' => 'Full Name',
    'email' => 'Email',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'phone' => 'Phone Number',
    'register' => 'Register',
    'already_have_account' => 'Already have an account?',
    'login_here' => 'Login here',
    'admin_email_restricted' => 'Admin email cannot be used.',
    'all_fields_required' => 'All fields are required.',
    'invalid_email' => 'Invalid email format.',
    'passwords_not_match' => 'Passwords do not match.',
    'email_exists' => 'Email already registered.',
    'account_created' => 'Account created successfully!',
    'error_try_again' => 'Error occurred. Please try again.',
  // Contact Us
  'contact_us' => 'Contact Us',
  'home' => 'Home',
  'first_name' => 'First Name',
  'last_name' => 'Last Name',
  'message' => 'What do you have in mind?',
  'message_placeholder' => 'Please enter Message...',
  'submit' => 'Submit',
  'fill_required_fields' => 'Please fill in all required fields.',
  'thank_you' => 'Thanks for contacting us,',
  'response_soon' => "We'll get back to you shortly.",
  'submission_error' => 'Oops! Something went wrong. Please try again later.',
  'valid_email' => 'Please enter a valid email address (example@example.com)',
  'valid_phone' => 'Please enter a 10-digit phone number',

  // Continue with the rest...


  //rep
     'latitude'     => 'Latitude',
    'longitude'    => 'Longitude',
    'address'      => 'Address',

    'html_lang'                    => 'en',
    'home'                         => 'Home',
    'volunteer'                    => 'Volunteer',
    'resource_collection'          => 'Resource Collection',
    'contact'                      => 'Contact',
    'about'                        => 'About',
    'blog'                         => 'Blog',

    'report_incident_title'        => 'Report New Incident',
    'report_incident_description'  => 'Provide details about the disaster incident and select its location on the map.',
    'incident_title'               => 'Incident Title',
    'description'                  => 'Description',
    'security_level'               => 'Security Level',
    'select_level'                 => 'Select Level',
    'low_level'                    => 'Low - Minor impact',
    'medium_level'                 => 'Medium - Moderate impact, several areas affected',
    'high_level'                   => 'High - Major impact, immediate response needed',
    'location'                     => 'Location',
    'click_map_instruction'        => 'Click on the map to select a location for the new incident.',
    'submit_incident'              => 'Submit Incident Report',
    'submitting'                   => 'Submitting your report...',
    'success_message'              => 'Incident submitted successfully!',

    'footer_title'                 => 'About Us',
    'footer_description'           => 'Our platform helps report, track, and respond quickly to disaster events.',
    'copyright'                    => '© 2025 Relief Sphere. All rights reserved.',


  //res
  'footer_title' => 'About Us',
  'footer_description' => 'Our platform helps report, track, and respond quickly to disaster events.',
  'copyright' => '© 2025 Relief Sphere. All rights reserved.',
  'resource_collection' => 'Resource Collection',
  'resource_type' => 'Resource Type',
  'select' => 'Select',
  'food' => 'Food',
  'water' => 'Water',
  'medicine' => 'Medicine',
  'shelter_kits' => 'Shelter Kits',
  'clothing' => 'Clothing',
  'quantity' => 'Quantity',
  'enter_quantity' => 'Enter quantity',
  'location' => 'Location',
  'enter_location' => 'Enter location',
  'submit' => 'Submit',
  'success_message' => 'Resource submitted successfully!',
  'error_message' => 'Error: ',
  'disaster_relief_platform' => 'Disaster Relief Platform',
  'platform_description' => 'Our platform helps report, track, and respond to disaster incidents in real time, promoting rapid action and recovery with community involvement.',
  'home' => 'Home',
  'about' => 'About',
  'contact' => 'Contact',
  'blog' => 'Blog',

  //volu
  'volunteer_page_title' => 'Become a Volunteer',
'volunteer_title' => 'Become a Volunteer',
'volunteer_fullname' => 'Full Name',
'volunteer_placeholder_name' => 'John Doe',
'volunteer_email' => 'Email',
'volunteer_placeholder_email' => 'email@example.com',
'volunteer_phone' => 'Phone Number',
'volunteer_placeholder_phone' => '123-456-7890',
'volunteer_city' => 'City',
'volunteer_placeholder_city' => 'Your City',
'volunteer_skills' => 'Skills',
'volunteer_placeholder_skills' => 'First Aid, Logistics, etc.',
'volunteer_availability' => 'Availability',
'volunteer_select_availability' => 'Select Availability',
'volunteer_weekdays' => 'Weekdays',
'volunteer_weekends' => 'Weekends',
'volunteer_anytime' => 'Anytime',
'volunteer_address' => 'Address',
'volunteer_placeholder_address' => 'Your Address...',
'volunteer_submit' => 'Submit',
'nav_resources' => 'Resources',       // English
'nav_about' => 'About',               // English
    // Main site strings
    'site_title' => 'Relief Sphere',
    'title_disaster_relief_platform'            => 'Disaster Relief Platform',
    'relief_sphere'                             => 'Relief Sphere',
    'alt_logo'                                  => 'Relief Sphere Logo',
    'about_us'                                  => 'About Us',
    'report_incident'                           => 'Report Incident',
    'volunteer'                                 => 'Volunteer',
    'resource_collection'                       => 'Resource Collection',
    'contact'                                   => 'Contact',
    'profile'                                   => 'Profile',
    'logout'                                    => 'Logout',
    
    // Navigation
    'nav_home'                                  => 'Home',
    'nav_report'                                => 'Report Incident',
    'nav_volunteer'                             => 'Volunteer',
    'nav_resource'                              => 'Resource Collection',
    'nav_contact'                               => 'Contact',
    'platform_name'                             => 'Disaster Relief Platform',
    
    // Hero section
    'hero_title'                                => 'Coordinating Disaster Relief Efficiently',
    'hero_subtitle'                             => 'Real-time data. Smarter help. Stronger communities.',
    
    // Key Features
    'key_features'                              => 'Key Features',
    'feature_realtime_alerts_title'             => 'Real-time Alerts',
    'feature_realtime_alerts_desc'              => 'Get notified immediately about disasters.',
    'feature_volunteer_system_title'            => 'Volunteer System',
    'feature_volunteer_system_desc'             => 'Easily join and help out during crises.',
    'feature_resource_coordination_title'       => 'Resource Coordination',
    'feature_resource_coordination_desc'        => 'Efficient management of resources.',
    
    // Disaster Awareness
    'disaster_awareness'                        => 'Disaster Awareness',
    'cyclone'                                   => 'Cyclone',
    'cyclone_info'                              => 'High-speed winds with heavy rains that can cause flooding and destruction...',
    'wildfire'                                  => 'Wildfire',
    'wildfire_info'                             => 'Uncontrolled fires in forests or grasslands...',
    'flood'                                     => 'Flood',
    'flood_info'                                => 'Rising water levels from heavy rain or dam overflow...',
    'earthquake'                                => 'Earthquake Response',
    'earthquake_info'                           => 'Learn what to do before, during, and after an earthquake...',
    'drought'                                   => 'Drought Relief',
    'drought_info'                              => 'Droughts cause water scarcity and crop failure...',
    'pandemic'                                  => 'Pandemic Preparedness',
    'pandemic_info'                             => 'Health disasters like pandemics need quick action...',

    // Footer
    'footer_resource_collection_title'          => 'Resource Collection',
    'footer_resource_collection_desc'           => 'Collect and distribute essential supplies.',
    'footer_volunteer_title'                    => 'Volunteer',
    'footer_volunteer_desc'                     => 'Become a volunteer and make a difference.',
    'footer_report_incident_title'              => 'Report Incident',
    'footer_report_incident_desc'               => 'Report incidents to get help fast.',
    'footer_blog'                               => 'Blog',
    'blog'                                      => 'Blog',
    'footer_rights'                             => 'Copyright ©2025 DisasterRelief',

    // Login related strings
    'login_title'                               => 'Login to Disaster Relief',
    'email_or_phone'                            => 'Email or Phone Number',
    'password'                                  => 'Password',
    'login_btn'                                 => 'Login',
    'create_account'                            => 'Create Account',
    'no_account'                                => "Don't have an account?",
    'invalid_password'                          => '❌ Invalid password!',
    'email_not_found'                           => '❌ Email or Phone number not found!',
    'invalid_email'                             => 'Please enter a valid email format.',
    'invalid_phone'                             => 'Please enter a valid phone number.',
];
