<?php
$lang = [

  //index
   // General
    'app_name' => 'Relief Sphere',
    'contact' => 'ബന്ധപ്പെടുക',
    'about_us' => 'ഞങ്ങളെ കുറിച്ച്',
    'report_incident' => 'സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'volunteer' => 'സേവകൻ',
    'resource_collection' => 'വിഭവ ശേഖരണം',

    // Hero Section
    'tagline_main' => 'ദുരന്ത ആശ്വാസം ഫലപ്രദമായി ഏകോപിപ്പിക്കുന്നു',
    'tagline_sub' => 'തത്സമയ ഡാറ്റ. കൂടുതൽ മെച്ചപ്പെട്ട സഹായം. ശക്തമായ സമൂഹങ്ങൾ.',

    // Features Section
    'key_features' => 'പ്രധാന സവിശേഷതകൾ',
    'real_time_alerts' => 'തത്സമയ മുന്നറിയിപ്പുകൾ',
    'real_time_alerts_desc' => 'ദുരന്തങ്ങളെക്കുറിച്ച് ഉടനെ അറിയപ്പെടുക.',
    'volunteer_system' => 'സേവക സമ്പ്രദായം',
    'volunteer_system_desc' => 'അപകടസമയത്ത് എളുപ്പത്തിൽ സേവനം നൽകുക.',
    'resource_coordination' => 'വിഭവ ഏകോപനം',
    'resource_coordination_desc' => 'വിഭവങ്ങളുടെ ഫലപ്രദമായ നിയന്ത്രണം.',

    // Action Cards
    'card_resource' => 'വിഭവ ശേഖരണം',
    'card_resource_desc' => 'അത്യാവശ്യ സാധനങ്ങൾ ശേഖരിക്കുകയും വിതരണം ചെയ്യുകയും ചെയ്യുക.',
    'card_volunteer' => 'സേവകൻ',
    'card_volunteer_desc' => 'ഒരു സേവകനായി ചേരുക, മാറ്റമുണ്ടാക്കുക.',
    'card_report' => 'സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'card_report_desc' => 'ഉടൻ സഹായം ലഭിക്കുന്നതിന് സംഭവങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക.',

    // Footer
    'rights_reserved' => '© 2025',
  //reg
  'create_account' => 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'full_name' => 'പൂര്‍ണനാമം',
    'email' => 'ഇമെയിൽ',
    'password' => 'പാസ്‌വേഡ്',
    'confirm_password' => 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'phone' => 'ഫോൺ നമ്പർ',
    'register' => 'രജിസ്റ്റർ ചെയ്യുക',
    'already_have_account' => 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    'login_here' => 'ഇവിടെ ലോഗിൻ ചെയ്യുക',
    'all_fields_required' => 'എല്ലാ ഫീൽഡുകളും ആവശ്യമുണ്ട്.',
    'invalid_email' => 'അസാധുവായ ഇമെയിൽ ഫോർമാറ്റ്.',
    'passwords_not_match' => 'പാസ്‌വേഡുകൾ ഒത്തില്ല.',
    'email_exists' => 'ഇമെയിൽ ഇതിനകം നിലവിലുണ്ട്.',
    'account_created' => 'അക്കൗണ്ട് വിജയകരമായി സൃഷ്ടിച്ചു',
    'error_try_again' => 'പിശക് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക.',
    'admin_email_restricted' => 'ഈ ഇമെയിൽ ഉപയോഗിച്ച് രജിസ്റ്റർ ചെയ്യാൻ കഴിയില്ല.',
  //con
   'contact_us' => 'ബന്ധപ്പെടുക',
    'home' => 'ഹോം',
    'first_name' => 'പേരിന്റെ ആദ്യഭാഗം',
    'last_name' => 'പേരിന്റെ അവസാനഭാഗം',
    'email' => 'ഇമെയിൽ',
    'phone' => 'ഫോൺ നമ്പർ',
    'message' => 'നിങ്ങളുടെ മനസ്സിൽ എന്താണ്?',
    'message_placeholder' => 'ദയവായി സന്ദേശം നൽകുക...',
    'submit' => 'സമർപ്പിക്കുക',
    'fill_required_fields' => 'ആവശ്യമായ എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക.',
    'invalid_email' => 'അസാധുവായ ഇമെയിൽ വിലാസം.',
    'thank_you' => 'ബന്ധപ്പെടുന്നതിന് നന്ദി,',
    'response_soon' => 'നാം ഉടൻ തന്നെ നിങ്ങളുമായി ബന്ധപ്പെടും.',
    'submission_error' => 'ഒരുതരത്തിൽ പിഴവുണ്ടായി. ദയവായി പിന്നീട് ശ്രമിക്കുക.',
    'valid_email' => 'ദയവായി സാധുവായ ഇമെയിൽ നൽകുക (example@example.com)',
    'valid_phone' => 'ദയവായി 10 അക്കമുള്ള ഫോൺ നമ്പർ നൽകുക',
  //rep
      'latitude'     => 'അക്ഷാംശം',
    'longitude'    => 'രേഖാംശം',
    'address'      => 'വിലാസം',

    'html_lang'                    => 'ml',
    'home'                         => 'ഹോം',
    'volunteer'                    => 'സന്നദ്ധസേവകൻ',
    'resource_collection'          => 'വിഭവ ശേഖരണം',
    'contact'                      => 'ബന്ധപ്പെടുക',
    'about'                        => 'ഞങ്ങളെക്കുറിച്ച്',
    'blog'                         => 'ബ്ലോഗ്',

    'report_incident_title'        => 'പുതിയ സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'report_incident_description'  => 'ദുരന്ത സംഭവത്തിന്റെ വിശദാംശങ്ങൾ നൽകുകയും ഭൂപടത്തിൽ അതിന്റെ സ്ഥലം തിരഞ്ഞെടുക്കുകയും ചെയ്യുക.',
    'incident_title'               => 'സംഭവം തലക്കെട്ട്',
    'description'                  => 'വിവരണം',
    'security_level'               => 'സുരക്ഷാ നില',
    'select_level'                 => 'നില തിരഞ്ഞെടുക്കുക',
    'low_level'                    => 'കുറഞ്ഞത് - ലഘു ബാധ',
    'medium_level'                 => 'ഇടത്തരം - മിതമായ ബാധ, പല മേഖലകളും ബാധിതം',
    'high_level'                   => 'ഉയരം - ഗുരുതര ബാധ, അടിയന്തര പ്രതികരണം ആവശ്യമാണ്',
    'location'                     => 'സ്ഥലം',
    'click_map_instruction'        => 'പുതിയ സംഭവത്തിന്റെ സ്ഥാനം തിരഞ്ഞെടുക്കാൻ ഭൂപടത്തിൽ ക്ലിക്ക് ചെയ്യുക.',
    'submit_incident'              => 'സംഭവ റിപ്പോർട്ട് സമർപ്പിക്കുക',
    'submitting'                   => 'നിങ്ങളുടെ റിപ്പോർട്ട് സമർപ്പിക്കുകയാണ്...',
    'success_message'              => 'സംഭവം വിജയകരമായി സമർപ്പിച്ചു!',

    'footer_title'                 => 'ഞങ്ങളെക്കുറിച്ച്',
    'footer_description'           => 'നമ്മുടെ പ്ലാറ്റ്‌ഫോം ദുരന്തങ്ങൾ റിപ്പോർട്ട് ചെയ്യാനും ട്രാക്ക് ചെയ്യാനും ത്വരിത പ്രതികരണത്തിനും സഹായിക്കുന്നു.',
    'copyright'                    => '© 2025 റിലീഫ് സ്ഫിയർ. എല്ലാ അവകാശങ്ങളും സംരക്ഷിതമാണ്.',


  //res
  'resource_collection' => 'വിഭവ ശേഖരണം',
  'resource_type' => 'വിഭവ തരം',
  'select' => 'തിരഞ്ഞെടുക്കുക',
  'food' => 'ഭക്ഷണം',
  'water' => 'വെള്ളം',
  'medicine' => 'മരുന്ന്',
  'shelter_kits' => 'വാസസ്ഥല കിറ്റ്',
  'clothing' => 'വസ്ത്രം',
  'quantity' => 'അളവ്',
  'enter_quantity' => 'അളവ് നൽകുക',
  'location' => 'സ്ഥലം',
  'enter_location' => 'സ്ഥലം നൽകുക',
  'submit' => 'സമർപ്പിക്കുക',
  'success_message' => 'വിഭവം വിജയകരമായി സമർപ്പിച്ചു!',
  'error_message' => 'പിഴവ്: ',
  'disaster_relief_platform' => 'പ്രളയ സഹായ പ്ലാറ്റ്ഫോം',
  'platform_description' => 'നമ്മുടെ പ്ലാറ്റ്ഫോം പ്രളയ സംഭവങ്ങൾ റിപ്പോർട്ട് ചെയ്യാനും ട്രാക്ക് ചെയ്യാനും സമൂഹത്തിന്റെ സഹകരണത്തോടെ ദ്രുതപ്രവർത്തനത്തിനും പുനരുദ്ധാരണത്തിനും സഹായിക്കുന്നു.',
  'home' => 'ഹോം',
  'about' => 'അവകാശം',
  'contact' => 'ബന്ധപ്പെടുക',
  'blog' => 'ബ്ലോഗ്',
  'footer_title' => 'ഞങ്ങളെക്കുറിച്ചു',
  'footer_description' => 'നമ്മുടെ പ്ലാറ്റ്ഫോം ദുരന്തങ്ങൾ റിപ്പോർട്ട് ചെയ്യാനും, ട്രാക്ക് ചെയ്യാനും, ത്വരിത പ്രതികരണത്തിനും സഹായിക്കുന്നു.',
  'copyright' => '© 2025 റിലീഫ് സ്ഫിയർ. എല്ലാ അവകാശങ്ങളും സംരക്ഷിതമാണ്.',
  //vo
  'nav_resources' => 'സ്രോതസ്സ്',
'nav_about' => 'പരിചയം',
  'volunteer_page_title' => 'സന്നദ്ധസേവകൻ ആയി മാറുക',
'volunteer_title' => 'സന്നദ്ധസേവകൻ ആയി മാറുക',
'volunteer_fullname' => 'പൂർണ്ണനാമം',
'volunteer_placeholder_name' => 'ജോൺ ഡോ',
'volunteer_email' => 'ഇമെയിൽ',
'volunteer_placeholder_email' => 'email@example.com',
'volunteer_phone' => 'ഫോൺ നമ്പർ',
'volunteer_placeholder_phone' => '123-456-7890',
'volunteer_city' => 'നഗരം',
'volunteer_placeholder_city' => 'നിങ്ങളുടെ നഗരം',
'volunteer_skills' => 'ശേഷികൾ',
'volunteer_placeholder_skills' => 'ഫസ്റ്റ് എയിഡ്, ലോജിസ്റ്റിക്സ് തുടങ്ങിയവ',
'volunteer_availability' => 'ലഭ്യത',
'volunteer_select_availability' => 'ലഭ്യത തിരഞ്ഞെടുക്കുക',
'volunteer_weekdays' => 'വാരദിനങ്ങൾ',
'volunteer_weekends' => 'വാരാന്ത്യങ്ങൾ',
'volunteer_anytime' => 'എപ്പോൾ വേണമെങ്കിലും',
'volunteer_address' => 'വിലാസം',
'volunteer_placeholder_address' => 'നിങ്ങളുടെ വിലാസം...',
'volunteer_submit' => 'സമർപ്പിക്കുക',

  //hom
  'platform_name' => 'ദുരന്താശ്വാസ വേദി',
  'title_disaster_relief_platform' => 'ദുരന്ത സഹായ പ്ലാറ്റ്‌ഫോം',
    'alt_logo' => 'റിലീഫ് സ്‌ഫിയർ ലോഗോ',
    'relief_sphere' => 'റിലീഫ് സ്‌ഫിയർ',
    'about_us' => 'ഞങ്ങളെ കുറിച്ച്',
    'report_incident' => 'സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'volunteer' => 'സ്വയംസേവകൻ',
    'resource_collection' => 'സ്രോതസ്സുകളുടെ ശേഖരണം',
    'contact' => 'ബന്ധപ്പെടുക',
    'profile' => 'പ്രൊഫൈൽ',
    'logout' => 'ലോഗൗട്ട്',
    'hero_title' => 'റിലീഫ് സ്‌ഫിയറിൽ സ്വാഗതം',
    'hero_subtitle' => 'നിങ്ങളുടെ വിശ്വസ്ത ദുരന്ത സഹായ പങ്കാളി',
    'key_features' => 'പ്രധാന സവിശേഷതകൾ',
    'feature_realtime_alerts_title' => 'തൽക്ഷണ അറിയിപ്പുകൾ',
    'feature_realtime_alerts_desc' => 'ദുരന്തങ്ങളേക്കുറിച്ചുള്ള തൽക്ഷണ അറിയിപ്പുകൾ ലഭിയ്ക്കുക.',
    'feature_volunteer_system_title' => 'സ്വയംസേവക സംവിധാനം',
    'feature_volunteer_system_desc' => 'ആപത്തിൽ സഹായിക്കാൻ എളുപ്പത്തിൽ ചേരുക.',
    'feature_resource_coordination_title' => 'സ്രോതസ്സുകളുടെ ഏകീകരണം',
    'feature_resource_coordination_desc' => 'സ്രോതസ്സുകൾ ഫലപ്രദമായി കൈകാര്യം ചെയ്യുക.',
    'footer_resource_collection_title' => 'സ്രോതസ്സുകളുടെ ശേഖരണം',
    'footer_resource_collection_desc' => 'അവശ്യ സാധനങ്ങൾ ശേഖരിച്ചു പങ്കുവെക്കുക.',
    'footer_volunteer_title' => 'സ്വയംസേവകൻ',
    'footer_volunteer_desc' => 'സ്വയംസേവകനായി വ്യത്യാസം ഉണ്ടാക്കൂ.',
    'footer_report_incident_title' => 'സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'footer_report_incident_desc' => 'തൽക്ഷണ സഹായത്തിനായി സംഭവങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക.',
    'blog' => 'ബ്ലോഗ്',
    'login_title' => 'ദുരന്ത സഹായത്തിനായി ലോഗിൻ ചെയ്യുക',
    'email_or_phone' => 'ഇമെയിൽ അല്ലെങ്കിൽ ഫോൺ നമ്പർ',
    'password' => 'പാസ്വേഡ്',
    'login_btn' => 'ലോഗിൻ',
    'create_account' => 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'no_account' => 'അക്കൗണ്ട് ഇല്ലേ?',
    'invalid_password' => '❌ തെറ്റായ പാസ്‌വേഡ്!',
    'email_not_found' => '❌ ഇമെയിൽ അല്ലെങ്കിൽ ഫോൺ നമ്പർ ലഭ്യമല്ല!',
    'invalid_email' => 'ദയവായി സാധുവായ ഇമെയിൽ നൽകുക.',
    'invalid_phone' => 'ദയവായി സാധുവായ ഫോൺ നമ്പർ നൽകുക.',
    //update 
      'platform_title' => 'റിലീഫ് സ്ഫിയർ - ദുരന്ത സഹായ പ്ലാറ്റ്ഫോം',
  'site_title' => 'റിലീഫ് സ്ഫിയർ',
  'nav_home' => 'ഹോം',
  'nav_report' => 'റിപ്പോർട്ട്',
  'nav_volunteer' => 'സ്വമേധയാ സേവനം',
  'nav_resource' => 'സ്രോതസ്സുകൾ',
  'nav_contact' => 'ബന്ധപ്പെടുക',
  'hero_title' => 'ദുരന്ത സഹായം ആരംഭിക്കുന്നു',
  'hero_subtitle' => 'നമുക്ക് ഒന്നിച്ച് സഹായിക്കാം, ജീവിതങ്ങൾ രക്ഷിക്കാം.',
  'disaster_awareness' => 'ദുരന്ത അവബോധം',
  'cyclone' => 'ചുഴലിക്കാറ്റ്',
  'cyclone_info' => 'ചുഴലിക്കാറ്റ് വന്നാൽ സുരക്ഷിത സ്ഥാനത്തേക്ക് പോയി, പൊതുജനപ്രദേശങ്ങളിൽ നിന്ന് അകലം പാലിക്കുക.',
  'wildfire' => 'കാടുതീ',
  'wildfire_info' => 'കാടുതീ സംഭവിക്കുന്ന പ്രദേശങ്ങളിൽ നിന്ന് ഒഴിഞ്ഞ് പോകുക, പുക ശ്വസിക്കുന്നത് ഒഴിവാക്കുക.',
  'flood' => 'പെരുമഴ',
  'flood_info' => 'വെള്ളപ്പൊക്കമുണ്ടായാൽ ഉയർന്ന സ്ഥലങ്ങളിലേക്ക് നീങ്ങുക, വൈദ്യുത ഉപകരണങ്ങളിൽ സ്പർശിക്കരുത്.',
  'earthquake' => 'ഭൂചലനം',
  'earthquake_info' => 'ഭൂചലന സമയത്ത് میزക്കുടയുടെ താഴെ ഒളിക്കുക അല്ലെങ്കിൽ തുറസ്സായ സ്ഥലത്ത് പോവുക.',
  'drought' => 'വിയർക്കൽ',
  'drought_info' => 'വിയർക്കലിനിടെ ജല സംരക്ഷണം അത്യന്താപേക്ഷിതമാണ്. വെള്ളം മോസമായി ഉപയോഗിക്കരുത്.',
  'pandemic' => 'പാൻഡെമിക്',
  'pandemic_info' => 'പാൻഡെമിക് സമയത്ത് മാസ്‌ക് ധരിക്കുക, കൈകൾ ശുദ്ധീകരിക്കുക, സാമൂഹിക അകലം പാലിക്കുക.',
  'footer_rights' => '© 2025 റിലീഫ് സ്ഫിയർ - എല്ലാ അവകാശങ്ങളും സംരക്ഷിച്ചിരിക്കുന്നു.',
  'footer_blog' => 'ബ്ലോഗ്',

// There is an extra comma before this line: remove the one from the previous line if not needed.
    // Main site strings
    'site_title' => 'റിലീഫ് സ്ഫിയർ',
    'alt_logo'                                 => 'റീലിയഫ് സ്ഫിയർ ലോഗോ',
    'relief_sphere'                            => 'റീലിയഫ് സ്ഫിയർ',
    'about_us'                                 => 'ഞങ്ങളെക്കുറിച്ച്',
    'report_incident'                          => 'സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'volunteer'                                => 'സന്നദ്ധസേവകൻ',
    'resource_collection'                      => 'സമ്പത്ത് ശേഖരണം',
    'contact'                                  => 'ബന്ധപ്പെടുക',
    'profile'                                  => 'പ്രൊഫൈൽ',
    'logout'                                   => 'ലോഗ് ഔട്ട്',
    'hero_title'                               => 'റീലിയഫ് സ്ഫിയറിലേക്ക് സ്വാഗതം',
    'hero_subtitle'                            => 'നിങ്ങളുടെ വിശ്വസനീയമായ പ്രളയ നിവാരണ പങ്കാളി',
    'key_features'                             => 'പ്രധാന സവിശേഷതകൾ',
    'feature_realtime_alerts_title'            => 'തത്സമയം അലർട്ടുകൾ',
    'feature_realtime_alerts_desc'             => 'പ്രളയങ്ങളെ കുറിച്ച് ഉടൻ അറിയപ്പെടുക.',
    'feature_volunteer_system_title'            => 'സന്നദ്ധസേവക സംവിധാനങ്ങൾ',
    'feature_volunteer_system_desc'             => 'സഹായത്തിനായി എളുപ്പത്തിൽ ചേർക്കുക.',
    'feature_resource_coordination_title'       => 'സമ്പത്ത് ഏകോപനം',
    'feature_resource_coordination_desc'        => 'സമ്പത്തുകളുടെ ഫലപ്രദമായ മാനേജ്‌മെന്റ്.',
    'footer_resource_collection_title'           => 'സമ്പത്ത് ശേഖരണം',
    'footer_resource_collection_desc'            => 'അവശ്യ സാധനങ്ങൾ ശേഖരിച്ച് വിതരണം ചെയ്യുക.',
    'footer_volunteer_title'                      => 'സന്നദ്ധസേവകൻ',
    'footer_volunteer_desc'                       => 'സന്നദ്ധസേവകനായി മാറ്റം സൃഷ്ടിക്കുക.',
    'footer_report_incident_title'                => 'സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'footer_report_incident_desc'                 => 'ഉടൻ സഹായം ലഭിക്കുന്നതിനായി സംഭവങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക.',
    'blog'                                       => 'ബ്ലോഗ്',

    // Login related strings
    'login_title'                              => 'പ്രളയ സഹായത്തിനായി ലോഗിൻ ചെയ്യുക',
    'email_or_phone'                           => 'ഇമെയിൽ അല്ലെങ്കിൽ ഫോൺ നമ്പർ',
    'password'                                 => 'പാസ്വേഡ്',
    'login_btn'                                => 'ലോഗിൻ',
    'create_account'                           => 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'no_account'                               => 'അക്കൗണ്ട് ഇല്ലേ?',
    'invalid_password'                         => '❌ അസാധുവായ പാസ്‌വേഡ്!',
    'email_not_found'                          => '❌ ഇമെയിൽ അല്ലെങ്കിൽ ഫോൺ നമ്പർ കണ്ടെത്തിയില്ല!',
    'invalid_email'                            => 'ദയവായി സാധുവായ ഇമെയിൽ ഫോർമാറ്റ് നൽകുക.',
    'invalid_phone'                            => 'ദയവായി സാധുവായ ഫോൺ നമ്പർ നൽകുക.',
];
?>
