<?php
$lang = [
  //reg
  'create_account' => 'ಖಾತೆ ಸೃಷ್ಟಿಸಿ',
    'full_name' => 'ಪೂರ್ಣ ಹೆಸರು',
    'email' => 'ಇಮೇಲ್',
    'password' => 'ಗುಪ್ತಪದ',
    'confirm_password' => 'ಗುಪ್ತಪದದ ಖಚಿತತೆ',
    'phone' => 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'register' => 'ನೋಂದಣಿ',
    'already_have_account' => 'ಈಗಾಗಲೇ ಖಾತೆಯಿದೆ?',
    'login_here' => 'ಇಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ',
    'all_fields_required' => 'ಎಲ್ಲಾ ಫೀಲ್ಡ್‌ಗಳು ಅಗತ್ಯವಿವೆ.',
    'invalid_email' => 'ಅಮಾನ್ಯ ಇಮೇಲ್ ಸ್ವರೂಪ.',
    'passwords_not_match' => 'ಗುಪ್ತಪದಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.',
    'email_exists' => 'ಈ ಇಮೇಲ್ ಈಗಾಗಲೇ ಇದೆ.',
    'account_created' => 'ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ',
    'error_try_again' => 'ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'admin_email_restricted' => 'ಈ ಇಮೇಲ್‌ನಿಂದ ನೋಂದಾಯಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.',
  //con
 
    'contact_us' => 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    'home' => 'ಮುಖಪುಟ',
    'first_name' => 'ಮೊದಲ ಹೆಸರು',
    'last_name' => 'ಕೊನೆಯ ಹೆಸರು',
    'email' => 'ಇಮೇಲ್',
    'phone' => 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
    'message' => 'ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಏನಿದೆ?',
    'message_placeholder' => 'ದಯವಿಟ್ಟು ಸಂದೇಶ ನಮೂದಿಸಿ...',
    'submit' => 'ಸಲ್ಲಿಸು',
    'fill_required_fields' => 'ದಯವಿಟ್ಟು ಎಲ್ಲ ಅಗತ್ಯ ಫೀಲ್ಡ್‌ಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.',
    'invalid_email' => 'ಅಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸ.',
    'thank_you' => 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು,',
    'response_soon' => 'ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
    'submission_error' => 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    'valid_email' => 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ (example@example.com)',
    'valid_phone' => 'ದಯವಿಟ್ಟು 10 ಅಂಕಿಯ ದೂರವಾಣಿ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',

  //rep
 
  'html_lang'                    => 'kn',
  'site_title' => 'ರಿಲೀಫ್ ಸ್ಫಿಯರ್',
    'home'                         => 'ಮುಖಪುಟ',
    'volunteer'                    => 'ಸ್ವಯಂಸೇವಕ',
    'resource_collection'          => 'ಸಂಪನ್ಮೂಲ ಸಂಗ್ರಹಣೆ',
    'contact'                      => 'ಸಂಪರ್ಕ',
    'about'                        => 'ನಮ್ಮ ಬಗ್ಗೆ',
    'blog'                         => 'ಬ್ಲಾಗ್',

    'latitude'     => 'ಅಕ್ಷಾಂಶ',
    'longitude'    => 'ರೇಖಾಂಶ',
    'address'      => 'ವಿಳಾಸ',

    'report_incident_title'        => 'ಹೊಸ ಘಟನೆ ವರದಿ ಮಾಡಿ',
    'report_incident_description'  => 'ವಿಪತ್ತು ಘಟನೆ ವಿವರಗಳನ್ನು ನೀಡಿ ಮತ್ತು ನಕ್ಷೆಯಲ್ಲಿ ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ.',
    'incident_title'               => 'ಘಟನೆ ಶೀರ್ಷಿಕೆ',
    'description'                  => 'ವಿವರಣೆ',
    'security_level'               => 'ಭದ್ರತಾ ಮಟ್ಟ',
    'select_level'                 => 'ಮಟ್ಟ ಆಯ್ಕೆಮಾಡಿ',
    'low_level'                    => 'ತಗ್ಗು - ಸೂಕ್ಷ್ಮ ಪರಿಣಾಮ',
    'medium_level'                 => 'ಮಧ್ಯಮ - ಮಿತಿಗನ್ ಪರಿಣಾಮ, ಹಲವು ಪ್ರದೇಶಗಳು ಪ್ರಭಾವಿತ',
    'high_level'                   => 'ಹೆಚ್ಚು - ಪ್ರಮುಖ ಪರಿಣಾಮ, ತ್ವರಿತ ಪ್ರತಿಕ್ರಿಯೆ ಅಗತ್ಯ',
    'location'                     => 'ಸ್ಥಳ',
    'click_map_instruction'        => 'ಹೊಸ ಘಟನೆಗೆ ಸ್ಥಳ ಆಯ್ಕೆ ಮಾಡಲು ನಕ್ಷೆಯಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    'submit_incident'              => 'ಘಟನೆ ವರದಿ ಸಲ್ಲಿಸಿ',
    'submitting'                   => 'ನಿಮ್ಮ ವರದಿ ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    'success_message'              => 'ಘಟನೆ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',

    'footer_title'                 => 'ನಮ್ಮ ಬಗ್ಗೆ',
    'footer_description'           => 'ನಮ್ಮ ವೇದಿಕೆ ವಿಪತ್ತು ಘಟನಗಳನ್ನು ವರದಿ ಮಾಡಲು, ಟ್ರ್ಯಾಕ್ ಮತ್ತು ತ್ವರಿತ ಪ್ರತಿಕ್ರಿಯೆಗಾಗಿ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    'copyright'                    => '© 2025 ರಿಲೀಫ್ ಸ್ಫಿಯರ್. ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    


  //res
  'footer_title' => 'ನಮ್ಮ ಬಗ್ಗೆ',
  'footer_description' => 'ನಮ್ಮ ವೇದಿಕೆ ಪ್ರಳಯ ಘಟನಗಳನ್ನು ವರದಿ ಮಾಡಲು, ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ತ್ವರಿತ ಕ್ರಮಕ್ಕೆ ನೆರವಾಗುತ್ತದೆ.',
  'copyright' => '© 2025 Relief Sphere. ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
  'resource_collection' => 'ಸಂಪನ್ಮೂಲ ಸಂಗ್ರಹಣೆ',
  'resource_type' => 'ಸಂಪನ್ಮೂಲ ಪ್ರಕಾರ',
  'select' => 'ಆಯ್ಕೆಮಾಡಿ',
  'food' => 'ಆಹಾರ',
  'water' => 'ನೀರು',
  'medicine' => 'ಔಷಧಿ',
  'shelter_kits' => 'ಶಿಬಿರ ಕಿಟ್‌ಗಳು',
  'clothing' => 'ಉಡುಪು',
  'quantity' => 'ಪ್ರಮಾಣ',
  'enter_quantity' => 'ಪ್ರಮಾಣ ನಮೂದಿಸಿ',
  'location' => 'ಸ್ಥಳ',
  'enter_location' => 'ಸ್ಥಳ ನಮೂದಿಸಿ',
  'submit' => 'ಸಲ್ಲಿಸು',
  'success_message' => 'ಸಂಪನ್ಮೂಲ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',
  'error_message' => 'ದೋಷ: ',
  'disaster_relief_platform' => 'ಪ್ರಳಯ ಪರಿಹಾರ ವೇದಿಕೆ',
  'platform_description' => 'ನಮ್ಮ ವೇದಿಕೆ ಪ್ರಳಯ ಘಟನೆಗಳನ್ನು ವರದಿ ಮಾಡಲು, ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ತ್ವರಿತ ಕ್ರಿಯೆ ಹಾಗೂ ಪುನರುತ್ಥಾನವನ್ನು ಉತ್ತೇಜಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
  'home' => 'ಮನೆಯ ಪುಟ',
  'about' => 'ಬಗ್ಗೆ',
  'contact' => 'ಸಂಪರ್ಕ',
  'blog' => 'ಬ್ಲಾಗ್',
  //vol
  
  'nav_resources' => 'ಸಂಪನ್ಮೂಲಗಳು',
'nav_about' => 'ಪರಿಚಯ',
  'volunteer_page_title' => 'ಸ್ವಯಂಸೇವಕನಾಗಿ ಸೇರ್ಪಡೆ',
'volunteer_title' => 'ಸ್ವಯಂಸೇವಕನಾಗಿ ಸೇರ್ಪಡೆ',
'volunteer_fullname' => 'ಪೂರ್ಣ ಹೆಸರು',
'volunteer_placeholder_name' => 'ಜಾನ್ ಡೋ',
'volunteer_email' => 'ಇಮೇಲ್',
'volunteer_placeholder_email' => 'email@example.com',
'volunteer_phone' => 'ಫೋನ್ ಸಂಖ್ಯೆ',
'volunteer_placeholder_phone' => '123-456-7890',
'volunteer_city' => 'ನಗರ',
'volunteer_placeholder_city' => 'ನಿಮ್ಮ ನಗರ',
'volunteer_skills' => 'ದಕ್ಷತೆಗಳು',
'volunteer_placeholder_skills' => 'ಮೆಡಿಕಲ್ ನೆರವು, ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಇತ್ಯಾದಿ',
'volunteer_availability' => 'ಲಭ್ಯತೆ',
'volunteer_select_availability' => 'ಲಭ್ಯತೆ ಆಯ್ಕೆಮಾಡಿ',
'volunteer_weekdays' => 'ವಾರದ ದಿನಗಳು',
'volunteer_weekends' => 'ವಾರಾಂತ್ಯ',
'volunteer_anytime' => 'ಯಾವುದೇ ಸಮಯ',
'volunteer_address' => 'ವಿಳಾಸ',
'volunteer_placeholder_address' => 'ನಿಮ್ಮ ವಿಳಾಸ...',
'volunteer_submit' => 'ಸಲ್ಲಿಸು',

    // Main site strings
    'title_disaster_relief_platform'           => 'ಪ್ರಾಕೃತಿಕ ವಿಪತ್ತು ಪರಿಹಾರ ವೇದಿಕೆ',
    'alt_logo'                                 => 'ರಿಲೀಫ್ ಸ್ಫಿಯರ್ ಲೋಗೋ',
    'relief_sphere'                            => 'ರಿಲೀಫ್ ಸ್ಫಿಯರ್',
    'about_us'                                 => 'ನಮ್ಮ ಬಗ್ಗೆ',
    'report_incident'                          => 'ಘಟನೆ ವರದಿ ಮಾಡಿ',
    'volunteer'                                => 'ಸ್ವಯಂಸೇವಕ',
    'resource_collection'                      => 'ಸಂಪನ್ಮೂಲ ಸಂಗ್ರಹ',
    'contact'                                  => 'ಸಂಪರ್ಕಿಸಿ',
    'profile'                                  => 'ಪ್ರೊಫೈಲ್',
    'logout'                                   => 'ಲಾಗೌಟ್',

    // Navigation
    'nav_home'                                 => 'ಮುಖಪುಟ',
    'nav_report'                               => 'ಘಟನೆ ವರದಿ',
    'nav_volunteer'                            => 'ಸ್ವಯಂಸೇವಕ',
    'nav_resource'                             => 'ಸಂಪನ್ಮೂಲ ಸಂಗ್ರಹ',
    'nav_contact'                              => 'ಸಂಪರ್ಕಿಸಿ',
    'platform_name'                            => 'ವಿಪತ್ತು ಪರಿಹಾರ ವೇದಿಕೆ',

    // Hero section
    'hero_title'                               => 'ರಿಲೀಫ್ ಸ್ಫಿಯರ್‌ಗೆ ಸ್ವಾಗತ',
    'hero_subtitle'                            => 'ನಿಮ್ಮ ನಂಬಿಗಸ್ತ ವಿಪತ್ತು ಪರಿಹಾರ ಸಹಯೋಗಿ',

    // Key Features
    'key_features'                             => 'ಮುಖ್ಯ ಲಕ್ಷಣಗಳು',
    'feature_realtime_alerts_title'            => 'ನೇರ-ಸಮಯ ಎಚ್ಚರಿಕೆಗಳು',
    'feature_realtime_alerts_desc'             => 'ವಿಪತ್ತುಗಳ ಬಗ್ಗೆ ತಕ್ಷಣ ಅಧಿಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'feature_volunteer_system_title'           => 'ಸ್ವಯಂಸೇವಕ ವ್ಯವಸ್ಥೆ',
    'feature_volunteer_system_desc'            => 'ಸಂಕಟಗಳಲ್ಲಿ ಸಹಾಯ ಮಾಡಲು ಸುಲಭವಾಗಿ ಸೇರಿ.',
    'feature_resource_coordination_title'      => 'ಸಂಪನ್ಮೂಲ ಸಂಯೋಜನೆ',
    'feature_resource_coordination_desc'       => 'ಸಂಪನ್ಮೂಲಗಳನ್ನು ಪರಿಣಾಮಕಾರಿಯಾಗಿ ನಿರ್ವಹಿಸಿ.',

    // Disaster Awareness
    'disaster_awareness'                       => 'ವಿಪತ್ತು ಅರಿವು',
    'cyclone'                                  => 'ಚಂಡಮಾರುತ',
    'cyclone_info'                             => 'ಗಂಭೀರ ಮಳೆ ಮತ್ತು ಗಾಳಿ, ಬೆಳೆ ಹಾನಿಗೆ ಕಾರಣ...',
    'wildfire'                                 => 'ಅರಣ್ಯ ಆಕಸ್ಮಿಕ',
    'wildfire_info'                            => 'ಅರಣ್ಯಗಳಲ್ಲಿ ನಿಯಂತ್ರಣವಿಲ್ಲದ ಬೆಂಕಿ ಹರಡುವಿಕೆ...',
    'flood'                                    => 'ಹೊರೆಹೊರೆ',
    'flood_info'                               => 'ಗಂಭೀರ ಮಳೆಯ ಅಥವಾ ಅಣೆಕಟ್ಟಿನ ಹರಿವುದಿಂದ ನೀರಿನ ಮಟ್ಟ ಹೆಚ್ಚಾಗುವುದು...',
    'earthquake'                               => 'ಭೂಕಂಪ',
    'earthquake_info'                          => 'ಭೂಕಂಪದ ಮೊದಲು, ಸಮಯದಲ್ಲಿ ಮತ್ತು ನಂತರ ಏನು ಮಾಡಬೇಕು ಎಂಬ ಮಾಹಿತಿ...',
    'drought'                                  => 'ಬಿಸಿಲುಗಾಲು',
    'drought_info'                             => 'ಮಳೆಯ ಕೊರತೆ, ಬೆಳೆ ನಾಶ, ನೀರಿನ ಕೊರತೆ...',
    'pandemic'                                 => 'ಸಾಂಕ್ರಾಮಿಕ',
    'pandemic_info'                            => 'ಸಾಂಕ್ರಾಮಿಕ ರೋಗಗಳಿಗೆ ತ್ವರಿತ ಪ್ರತಿಕ್ರಿಯೆ ಅಗತ್ಯವಿದೆ...',

    // Footer
    'footer_resource_collection_title'         => 'ಸಂಪನ್ಮೂಲ ಸಂಗ್ರಹ',
    'footer_resource_collection_desc'          => 'ಅತ್ಯಾವಶ್ಯಕ ಸರಕುಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ ಹಂಚಿಕೊಳ್ಳಿ.',
    'footer_volunteer_title'                   => 'ಸ್ವಯಂಸೇವಕ',
    'footer_volunteer_desc'                    => 'ಸ್ವಯಂಸೇವಕರಾಗಿ ಭಿನ್ನತೆಯನ್ನು ಸೃಷ್ಟಿಸಿ.',
    'footer_report_incident_title'             => 'ಘಟನೆ ವರದಿ ಮಾಡಿ',
    'footer_report_incident_desc'              => 'ತ್ವರಿತ ನೆರವಿಗಾಗಿ ಘಟನೆಗಳನ್ನು ವರದಿ ಮಾಡಿ.',
    'footer_blog'                              => 'ಬ್ಲಾಗ್',
    'blog'                                     => 'ಬ್ಲಾಗ್',
    'footer_rights'                            => 'ಮೂಲಸ್ಪರ್ಧೆ ©2025 ವಿಪತ್ತು ಪರಿಹಾರ',

    // Login related strings
    'login_title'                              => 'ವಿಪತ್ತು ಪರಿಹಾರಕ್ಕೆ ಲಾಗಿನ್ ಆಗಿ',
    'email_or_phone'                           => 'ಇಮೇಲ್ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆ',
    'password'                                 => 'ಗುಪ್ತಪದ',
    'login_btn'                                => 'ಲಾಗಿನ್',
    'create_account'                           => 'ಖಾತೆಯನ್ನು ರಚಿಸಿ',
    'no_account'                               => 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'invalid_password'                         => '❌ ಅಮಾನ್ಯ ಪಾಸ್ವರ್ಡ್!',
    'email_not_found'                          => '❌ ಇಮೇಲ್ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆ ಕಂಡುಬರಲಿಲ್ಲ!',
    'invalid_email'                            => 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಇಮೇಲ್ ನಮೂನೆಯನ್ನು ನಮೂದಿಸಿ.',
    'invalid_phone'                            => 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
];
?>
