<?php
$lang = [
  //reg
  'create_account' => 'खाता बनाएं',
    'full_name' => 'पूरा नाम',
    'email' => 'ईमेल',
    'password' => 'पासवर्ड',
    'confirm_password' => 'पासवर्ड की पुष्टि करें',
    'phone' => 'फ़ोन नंबर',
    'register' => 'पंजीकरण करें',
    'already_have_account' => 'पहले से ही खाता है?',
    'login_here' => 'यहाँ लॉगिन करें',
    'all_fields_required' => 'सभी फ़ील्ड आवश्यक हैं।',
    'invalid_email' => 'अमान्य ईमेल प्रारूप।',
    'passwords_not_match' => 'पासवर्ड मेल नहीं खाते।',
    'email_exists' => 'ईमेल पहले से मौजूद है।',
    'account_created' => 'खाता सफलतापूर्वक बनाया गया',
    'error_try_again' => 'कुछ त्रुटि हुई। कृपया पुनः प्रयास करें।',
    'admin_email_restricted' => 'आप इस ईमेल से पंजीकरण नहीं कर सकते।',
  //con
 
    'contact_us' => 'संपर्क करें',
    'home' => 'होम',
    'first_name' => 'पहला नाम',
    'last_name' => 'अंतिम नाम',
    'email' => 'ईमेल',
    'phone' => 'फ़ोन नंबर',
    'message' => 'आपके मन में क्या है?',
    'message_placeholder' => 'कृपया संदेश दर्ज करें...',
    'submit' => 'सबमिट करें',
    'fill_required_fields' => 'कृपया सभी आवश्यक फ़ील्ड भरें।',
    'invalid_email' => 'अमान्य ईमेल पता।',
    'thank_you' => 'हमसे संपर्क करने के लिए धन्यवाद,',
    'response_soon' => 'हम शीघ्र ही आपसे संपर्क करेंगे।',
    'submission_error' => 'कुछ गलत हो गया। कृपया बाद में प्रयास करें।',
    'valid_email' => 'कृपया मान्य ईमेल पता दर्ज करें (example@example.com)',
    'valid_phone' => 'कृपया 10-अंकों का फ़ोन नंबर दर्ज करें',

  //rep
    'latitude'     => 'Latitude',
    'longitude'    => 'Longitude',
    'address'      => 'Address',

    'html_lang'                    => 'hi',
    'home'                         => 'मुखपृष्ठ',
    'volunteer'                    => 'स्वयंसेवक',
    'resource_collection'          => 'संसाधन संग्रह',
    'contact'                      => 'संपर्क करें',
    'about'                        => 'हमारे बारे में',
    'blog'                         => 'ब्लॉग',

    'report_incident_title'        => 'नई घटना रिपोर्ट करें',
    'report_incident_description'  => 'आपदा घटना का विवरण प्रदान करें और मानचित्र पर इसका स्थान चुनें।',
    'incident_title'               => 'घटना शीर्षक',
    'description'                  => 'विवरण',
    'security_level'               => 'सुरक्षा स्तर',
    'select_level'                 => 'स्तर चुनें',
    'low_level'                    => 'निम्न - मामूली प्रभाव',
    'medium_level'                 => 'मध्यम - मध्यम प्रभाव, कई क्षेत्रों में प्रभावित',
    'high_level'                   => 'उच्च - गंभीर प्रभाव, तत्काल प्रतिक्रिया आवश्यक',
    'location'                     => 'स्थान',
    'click_map_instruction'        => 'नई घटना के स्थान के लिए मानचित्र पर क्लिक करें।',
    'submit_incident'              => 'घटना रिपोर्ट जमा करें',
    'submitting'                   => 'आपकी रिपोर्ट जमा की जा रही है...',
    'success_message'              => 'घटना सफलतापूर्वक जमा की गई!',

    'footer_title'                 => 'हमारे बारे में',
    'footer_description'           => 'हमारा प्लेटफ़ॉर्म आपदा घटनाओं की रिपोर्ट, ट्रैकिंग और त्वरित प्रतिक्रिया में मदद करता है।',
    'copyright'                    => '© 2025 रिलीफ स्फीयर। सर्वाधिकार सुरक्षित।',


  //rep
  "report_incident_title" => "नई घटना की रिपोर्ट करें",
  "incident_instruction" => "आपदा घटना का विवरण प्रदान करें और मानचित्र पर उसका स्थान चुनें।",
  "incident_title" => "घटना शीर्षक",
  "incident_description" => "विवरण",
  "security_level" => "सुरक्षा स्तर",
  "select_level" => "स्तर चुनें",
  "low_level" => "निम्न - मामूली प्रभाव",
  "medium_level" => "मध्यम - मध्यम प्रभाव, कई क्षेत्र प्रभावित",
  "high_level" => "उच्च - बड़ा प्रभाव, तुरंत प्रतिक्रिया आवश्यक",
  "location_label" => "स्थान",
  "map_instruction" => "नई घटना के लिए मानचित्र पर स्थान क्लिक करें।",
  "latitude" => "अक्षांश",
  "longitude" => "देशांतर",
  "address" => "पता",
  "submit_incident" => "घटना रिपोर्ट सबमिट करें",
  "submitting_report" => "आपकी रिपोर्ट सबमिट की जा रही है...",
  "success_message" => "✅ घटना सफलतापूर्वक सबमिट की गई!",
  //res
  'footer_title' => 'हमारे बारे में',
  'footer_description' => 'हमारा प्लेटफ़ॉर्म आपदाओं की रिपोर्ट करने, ट्रैक करने और त्वरित प्रतिक्रिया देने में मदद करता है।',
  'copyright' => '© 2025 रिलीफ स्फीयर। सर्वाधिकार सुरक्षित।',
  'resource_collection' => 'संसाधन संग्रह',
  'resource_type' => 'संसाधन प्रकार',
  'select' => 'चुनें',
  'food' => 'भोजन',
  'water' => 'पानी',
  'medicine' => 'दवा',
  'shelter_kits' => 'आश्रय किट',
  'clothing' => 'कपड़े',
  'quantity' => 'मात्रा',
  'enter_quantity' => 'मात्रा दर्ज करें',
  'location' => 'स्थान',
  'enter_location' => 'स्थान दर्ज करें',
  'submit' => 'जमा करें',
  'success_message' => 'संसाधन सफलतापूर्वक जमा किए गए!',
  'error_message' => 'त्रुटि: ',
  'disaster_relief_platform' => 'आपदा राहत प्लेटफ़ॉर्म',
  'platform_description' => 'हमारा प्लेटफ़ॉर्म आपदा घटनाओं की रिपोर्ट, ट्रैकिंग और त्वरित कार्रवाई और पुनर्प्राप्ति को बढ़ावा देने में सहायता करता है।',
  'home' => 'मुखपृष्ठ',
  'about' => 'हमारे बारे में',
  'contact' => 'संपर्क करें',
  'blog' => 'ब्लॉग',
  //vo
  'nav_resources' => 'संसाधन',
'nav_about' => 'हमारे बारे में',

  'volunteer_page_title' => 'स्वयंसेवक बनें',
'volunteer_title' => 'स्वयंसेवक बनें',
'volunteer_fullname' => 'पूरा नाम',
'volunteer_placeholder_name' => 'जॉन डो',
'volunteer_email' => 'ईमेल',
'volunteer_placeholder_email' => 'email@example.com',
'volunteer_phone' => 'फोन नंबर',
'volunteer_placeholder_phone' => '123-456-7890',
'volunteer_city' => 'शहर',
'volunteer_placeholder_city' => 'आपका शहर',
'volunteer_skills' => 'कौशल',
'volunteer_placeholder_skills' => 'प्राथमिक चिकित्सा, लॉजिस्टिक्स आदि',
'volunteer_availability' => 'उपलब्धता',
'volunteer_select_availability' => 'उपलब्धता चुनें',
'volunteer_weekdays' => 'सप्ताह के दिन',
'volunteer_weekends' => 'सप्ताहांत',
'volunteer_anytime' => 'किसी भी समय',
'volunteer_address' => 'पता',
'volunteer_placeholder_address' => 'आपका पता...',
'volunteer_submit' => 'जमा करें',

  //home
  'platform_name' => 'आपदा राहत मंच',
  'title_disaster_relief_platform' => 'आपदा राहत मंच',
    'alt_logo' => 'रिलीफ स्फीयर लोगो',
    'relief_sphere' => 'रिलीफ स्फीयर',
    'about_us' => 'हमारे बारे में',
    'report_incident' => 'घटना रिपोर्ट करें',
    'volunteer' => 'स्वयंसेवक',
    'resource_collection' => 'संसाधन संग्रह',
    'contact' => 'संपर्क करें',
    'profile' => 'प्रोफ़ाइल',
    'logout' => 'लॉगआउट',
    'hero_title' => 'रिलीफ स्फीयर में आपका स्वागत है',
    'hero_subtitle' => 'आपका भरोसेमंद आपदा राहत साथी',
    'key_features' => 'मुख्य विशेषताएं',
    'feature_realtime_alerts_title' => 'रीयल-टाइम अलर्ट्स',
    'feature_realtime_alerts_desc' => 'आपदाओं के लिए तुरंत सूचनाएं प्राप्त करें।',
    'feature_volunteer_system_title' => 'स्वयंसेवक प्रणाली',
    'feature_volunteer_system_desc' => 'आपात स्थितियों में मदद करने के लिए आसानी से शामिल हों।',
    'feature_resource_coordination_title' => 'संसाधन समन्वय',
    'feature_resource_coordination_desc' => 'संसाधनों को कुशलता से प्रबंधित करें।',
    'footer_resource_collection_title' => 'संसाधन संग्रह',
    'footer_resource_collection_desc' => 'आवश्यक वस्तुओं को इकट्ठा करें और साझा करें।',
    'footer_volunteer_title' => 'स्वयंसेवक',
    'footer_volunteer_desc' => 'स्वयंसेवक बनकर बदलाव लाएं।',
    'footer_report_incident_title' => 'घटना रिपोर्ट करें',
    'footer_report_incident_desc' => 'त्वरित सहायता के लिए घटनाओं की रिपोर्ट करें।',
    'blog' => 'ब्लॉग',
    'login_title' => 'आपदा राहत में लॉगिन करें',
    'email_or_phone' => 'ईमेल या फोन नंबर',
    'password' => 'पासवर्ड',
    'login_btn' => 'लॉगिन',
    'create_account' => 'खाता बनाएं',
    'no_account' => 'कोई खाता नहीं है?',
    'invalid_password' => '❌ अमान्य पासवर्ड!',
    'email_not_found' => '❌ ईमेल या फोन नंबर नहीं मिला!',
    'invalid_email' => 'कृपया एक मान्य ईमेल पता दर्ज करें।',
    'invalid_phone' => 'कृपया एक मान्य फोन नंबर दर्ज करें।',
    //updated
    
  'platform_title' => 'रिलीफ स्फीयर - आपदा राहत मंच',
  'site_title' => 'रिलीफ स्फीयर',
  'nav_home' => 'होम',
  'nav_report' => 'रिपोर्ट करें',
  'nav_volunteer' => 'स्वयंसेवक बनें',
  'nav_resource' => 'संसाधन',
  'nav_contact' => 'संपर्क करें',
  'hero_title' => 'आपदा से निपटने के लिए एक साथ',
  'hero_subtitle' => 'आपात स्थितियों में सहायता और संसाधन प्रदान करना',
  'disaster_awareness' => 'आपदा जागरूकता',
  'cyclone' => 'चक्रवात',
  'cyclone_info' => 'तेज़ हवाओं और भारी वर्षा के साथ चक्रवात तटीय क्षेत्रों को नुकसान पहुंचा सकते हैं। सुरक्षित रहें और अलर्ट्स का पालन करें।',
  'wildfire' => 'वनाग्नि',
  'wildfire_info' => 'सूखे और गर्म मौसम में लगने वाली आग तेजी से फैल सकती है। खाली करने की योजना तैयार रखें।',
  'flood' => 'बाढ़',
  'flood_info' => 'भारी वर्षा या नदी के उफान के कारण बाढ़ आ सकती है। ऊंचे स्थानों पर जाना सुरक्षित होता है।',
  'earthquake' => 'भूकंप',
  'earthquake_info' => 'भूकंप अचानक आते हैं और इमारतों को नुकसान पहुंचा सकते हैं। सुरक्षित स्थान की योजना बनाएं।',
  'drought' => 'सूखा',
  'drought_info' => 'लंबे समय तक वर्षा न होने से सूखा पड़ता है जिससे पानी की कमी होती है। जल संरक्षण करें।',
  'pandemic' => 'महामारी',
  'pandemic_info' => 'महामारी के दौरान, मास्क पहनें, हाथ धोएं और सामाजिक दूरी बनाए रखें। सुरक्षित रहें।',
  'footer_rights' => '© 2025 रिलीफ स्फीयर। सभी अधिकार सुरक्षित।',
  'footer_blog' => 'आपदा ब्लॉग',

    // Main site strings
    'site_title' => 'रिलीफ़ स्फीयर',
    'title_disaster_relief_platform'           => 'आपदा राहत मंच',
    'alt_logo'                                 => 'रिलीफ स्फीयर लोगो',
    'relief_sphere'                            => 'रिलीफ स्फीयर',
    'about_us'                                 => 'हमारे बारे में',
    'report_incident'                          => 'घटना रिपोर्ट करें',
    'volunteer'                                => 'स्वयंसेवक',
    'resource_collection'                      => 'संसाधन संग्रह',
    'contact'                                  => 'संपर्क करें',
    'profile'                                  => 'प्रोफ़ाइल',
    'logout'                                   => 'लॉग आउट',
    'hero_title'                               => 'रिलीफ स्फीयर में आपका स्वागत है',
    'hero_subtitle'                            => 'आपका भरोसेमंद आपदा राहत साथी',
    'key_features'                             => 'मुख्य विशेषताएँ',
    'feature_realtime_alerts_title'            => 'रीयल-टाइम अलर्ट',
    'feature_realtime_alerts_desc'             => 'आपदाओं के बारे में तुरंत सूचित हों।',
    'feature_volunteer_system_title'            => 'स्वयंसेवक प्रणाली',
    'feature_volunteer_system_desc'             => 'संकट के दौरान आसानी से शामिल हों और मदद करें।',
    'feature_resource_coordination_title'       => 'संसाधन समन्वय',
    'feature_resource_coordination_desc'        => 'संसाधनों का कुशल प्रबंधन।',
    'footer_resource_collection_title'           => 'संसाधन संग्रह',
    'footer_resource_collection_desc'            => 'आवश्यक वस्तुओं को इकट्ठा करें और वितरित करें।',
    'footer_volunteer_title'                      => 'स्वयंसेवक',
    'footer_volunteer_desc'                       => 'स्वयंसेवक बनें और फर्क डालें।',
    'footer_report_incident_title'                => 'घटना रिपोर्ट करें',
    'footer_report_incident_desc'                 => 'जल्द सहायता पाने के लिए घटनाओं की रिपोर्ट करें।',
    'blog'                                       => 'ब्लॉग',

    // Login related strings
    'login_title'                              => 'आपदा राहत में लॉगिन करें',
    'email_or_phone'                           => 'ईमेल या फोन नंबर',
    'password'                                 => 'पासवर्ड',
    'login_btn'                                => 'लॉगिन',
    'create_account'                           => 'खाता बनाएं',
    'no_account'                               => 'खाता नहीं है?',
    'invalid_password'                         => '❌ अमान्य पासवर्ड!',
    'email_not_found'                          => '❌ ईमेल या फोन नंबर नहीं मिला!',
    'invalid_email'                            => 'कृपया एक मान्य ईमेल प्रारूप दर्ज करें।',
    'invalid_phone'                            => 'कृपया एक मान्य फोन नंबर दर्ज करें।',
];
?>
