<?php
$lang = [
  //reg
  'create_account' => 'கணக்கை உருவாக்குங்கள்',
    'full_name' => 'முழு பெயர்',
    'email' => 'மின்னஞ்சல்',
    'password' => 'கடவுச்சொல்',
    'confirm_password' => 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'phone' => 'தொலைபேசி எண்',
    'register' => 'பதிவு செய்யவும்',
    'already_have_account' => 'ஏற்கனவே கணக்கு உள்ளதா?',
    'login_here' => 'இங்கே உள்நுழைக',
    'all_fields_required' => 'அனைத்து புலங்களும் தேவை.',
    'invalid_email' => 'தவறான மின்னஞ்சல் வடிவம்.',
    'passwords_not_match' => 'கடவுச்சொற்கள் பொருந்தவில்லை.',
    'email_exists' => 'மின்னஞ்சல் ஏற்கனவே உள்ளது.',
    'account_created' => 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது',
    'error_try_again' => 'பிழை ஏற்பட்டது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    'admin_email_restricted' => 'இந்த மின்னஞ்சலைப் பயன்படுத்தி பதிவு செய்ய முடியாது.',
  //con

    'contact_us' => 'எங்களை தொடர்புகொள்ள',
    'home' => 'முகப்பு',
    'first_name' => 'முதல் பெயர்',
    'last_name' => 'கடைசி பெயர்',
    'email' => 'மின்னஞ்சல்',
    'phone' => 'தொலைபேசி எண்',
    'message' => 'உங்கள் மனதில் என்ன இருக்கிறது?',
    'message_placeholder' => 'தயவுசெய்து செய்தியை உள்ளிடவும்...',
    'submit' => 'சமர்ப்பிக்கவும்',
    'fill_required_fields' => 'தயவுசெய்து தேவையான அனைத்து பகுதிகளையும் நிரப்பவும்.',
    'invalid_email' => 'தவறான மின்னஞ்சல் முகவரி.',
    'thank_you' => 'எங்களை தொடர்புகொண்டதற்கு நன்றி,',
    'response_soon' => 'நாங்கள் விரைவில் உங்கள் தொடர்புக்கு பதிலளிப்போம்.',
    'submission_error' => 'ஏதோவொரு பிழை ஏற்பட்டது. தயவுசெய்து பின்னர் முயற்சிக்கவும்.',
    'valid_email' => 'தயவுசெய்து செல்லுபடியாகும் மின்னஞ்சல் முகவரியை உள்ளிடவும் (example@example.com)',
    'valid_phone' => 'தயவுசெய்து 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்',


  //rep
     'latitude'     => 'அட்சரேகை',
    'longitude'    => 'தீர்க்கரேகை',
    'address'      => 'முகவரி',

    'html_lang'                    => 'ta',
    'home'                         => 'முகப்பு',
    'volunteer'                    => 'தன்னார்வலர்',
    'resource_collection'          => 'வள சேகரிப்பு',
    'contact'                      => 'தொடர்பு',
    'about'                        => 'எங்களைப் பற்றி',
    'blog'                         => 'வலைப்பதிவு',

    'report_incident_title'        => 'புதிய நிகழ்வை அறிக்கையிடவும்',
    'report_incident_description'  => 'பேரழிவு சம்பவம் பற்றிய விவரங்களை வழங்கவும் மற்றும் வரைபடத்தில் இடத்தைத் தேர்ந்தெடுக்கவும்.',
    'incident_title'               => 'நிகழ்வு தலைப்பு',
    'description'                  => 'விபரம்',
    'security_level'               => 'பாதுகாப்பு நிலை',
    'select_level'                 => 'நிலையை தேர்வுசெய்க',
    'low_level'                    => 'குறைந்தது - சிறிய தாக்கம்',
    'medium_level'                 => 'இடைநிலை - மிதமான தாக்கம், பல பகுதிகள் பாதிக்கப்படும்',
    'high_level'                   => 'உயர்ந்தது - பெரிய தாக்கம், உடனடி பதில் தேவை',
    'location'                     => 'இடம்',
    'click_map_instruction'        => 'புதிய நிகழ்வுக்கான இடத்தை தேர்வுசெய்ய வரைபடத்தில் கிளிக் செய்க.',
    'submit_incident'              => 'நிகழ்வு அறிக்கையை சமர்ப்பிக்கவும்',
    'submitting'                   => 'உங்கள் அறிக்கை சமர்ப்பிக்கப்பட்டற்காக...',
    'success_message'              => 'நிகழ்வு வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',

    'footer_title'                 => 'எங்களைப் பற்றி',
    'footer_description'           => 'எங்கள் தளம் பேரழிவு சம்பவங்களை அறிக்கையிடவும், கண்காணிக்கவும் மற்றும் விரைவாக பதிலளிக்கவும் உதவுகிறது.',
    'copyright'                    => '© 2025 ரிலீஃப் ஸ்பியர். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',

  //res
  'footer_title' => 'எங்களைப் பற்றி',
  'footer_description' => 'எங்கள் தளம் பேரழிவுகளை அறிவிக்கவும், கண்காணிக்கவும் மற்றும் விரைவாக பதிலளிக்கவும் உதவுகிறது.',
  'copyright' => '© 2025 ரிலீஃப் ஸ்பியர். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
  'resource_collection' => 'வள சேகரிப்பு',
  'resource_type' => 'வள வகை',
  'select' => 'தேர்வு செய்க',
  'food' => 'உணவு',
  'water' => 'தண்ணீர்',
  'medicine' => 'மருந்து',
  'shelter_kits' => 'தஞ்சவீடு பொருட்கள்',
  'clothing' => 'ஆடைகள்',
  'quantity' => 'அளவு',
  'enter_quantity' => 'அளவு உள்ளிடவும்',
  'location' => 'இடம்',
  'enter_location' => 'இடத்தை உள்ளிடவும்',
  'submit' => 'சமர்ப்பிக்கவும்',
  'success_message' => 'வள வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
  'error_message' => 'பிழை: ',
  'disaster_relief_platform' => 'துயர தொலைத்தள தளம்',
  'platform_description' => 'எங்கள் தளம் துயர் சம்பவங்களை அறிக்கை செய்வதற்கும், கண்காணிப்பதற்கும் மற்றும் விரைவான நடவடிக்கை மற்றும் மீட்புக்காக சமூக பங்களிப்புடன் உதவுகிறது.',
  'home' => 'முகப்பு',
  'about' => 'பற்றி',
  'contact' => 'தொடர்பு',
  'blog' => 'வலைப்பதிவு',
  //v
  'volunteer_page_title' => 'தன்னார்வலராக இருக்கவும்',
'volunteer_title' => 'தன்னார்வலராக இருக்கவும்',
'volunteer_fullname' => 'முழு பெயர்',
'volunteer_placeholder_name' => 'ஜான் டோ',
'volunteer_email' => 'மின்னஞ்சல்',
'volunteer_placeholder_email' => 'email@example.com',
'volunteer_phone' => 'தொலைபேசி எண்',
'volunteer_placeholder_phone' => '123-456-7890',
'volunteer_city' => 'நகரம்',
'volunteer_placeholder_city' => 'உங்கள் நகரம்',
'volunteer_skills' => 'திறன்கள்',
'volunteer_placeholder_skills' => 'முதன்முதலில் உதவி, லாஜிஸ்டிக்ஸ், மற்றும் மற்றவை',
'volunteer_availability' => 'கிடைக்கும் நேரம்',
'volunteer_select_availability' => 'கிடைக்கும் நேரத்தை தேர்வு செய்யவும்',
'volunteer_weekdays' => 'வாரந்தோறும்',
'volunteer_weekends' => 'வார இறுதி',
'volunteer_anytime' => 'எப்போதும்',
'volunteer_address' => 'முகவரி',
'volunteer_placeholder_address' => 'உங்கள் முகவரி...',
'volunteer_submit' => 'சமர்ப்பிக்கவும்',
'nav_resources' => 'வளங்கள்',
'nav_about' => 'பற்றி',
  // home str
  'platform_name' => 'आपदा राहत मंच',
    'title_disaster_relief_platform' => 'பேரிடர் நிவாரண தளம்',
    'alt_logo' => 'ரிலீஃப் ஸ்பியர் லோகோ',
    'relief_sphere' => 'ரிலீஃப் ஸ்பியர்',
    'about_us' => 'எங்களை பற்றி',
    'report_incident' => 'சம்பவம் அறிக்கை',
    'volunteer' => 'தன்னார்வலர்',
    'resource_collection' => 'வள சேகரிப்பு',
    'contact' => 'தொடர்பு கொள்ள',
    'profile' => 'சுயவிவரம்',
    'logout' => 'வெளியேறு',
    'hero_title' => 'ரிலீஃப் ஸ்பியருக்கு வரவேற்கின்றோம்',
    'hero_subtitle' => 'உங்கள் நம்பகமான பேரிடர் நிவாரண கூட்டாளி',
    'key_features' => 'முக்கிய அம்சங்கள்',
    'feature_realtime_alerts_title' => 'நேரடி எச்சரிக்கைகள்',
    'feature_realtime_alerts_desc' => 'பேரிடர்களுக்கான உடனடி அறிவிப்புகளைப் பெறுங்கள்.',
    'feature_volunteer_system_title' => 'தன்னார்வலர் அமைப்பு',
    'feature_volunteer_system_desc' => 'அவசர நிலைகளில் உதவ எளிதாக சேருங்கள்.',
    'feature_resource_coordination_title' => 'வள ஒருங்கிணைப்பு',
    'feature_resource_coordination_desc' => 'வளங்களை திறமையாக நிர்வகிக்கவும்.',
    'footer_resource_collection_title' => 'வள சேகரிப்பு',
    'footer_resource_collection_desc' => 'அத்தியாவசிய பொருட்களை சேகரித்து பகிரவும்.',
    'footer_volunteer_title' => 'தன்னார்வலர்',
    'footer_volunteer_desc' => 'தன்னார்வலராக வேறுபாட்டை உருவாக்குங்கள்.',
    'footer_report_incident_title' => 'சம்பவம் அறிக்கை',
    'footer_report_incident_desc' => 'விரைந்து உதவ சம்பவங்களை அறிக்கையிடுங்கள்.',
    'blog' => 'ப்ளாக்',
    'login_title' => 'பேரிடர் நிவாரணத்திற்கு உள்நுழைக',
    'email_or_phone' => 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
    'password' => 'கடவுச்சொல்',
    'login_btn' => 'உள்நுழை',
    'create_account' => 'கணக்கை உருவாக்கு',
    'no_account' => 'கணக்கு இல்லையா?',
    'invalid_password' => '❌ தவறான கடவுச்சொல்!',
    'email_not_found' => '❌ மின்னஞ்சல் அல்லது தொலைபேசி எண் கிடைக்கவில்லை!',
    'invalid_email' => 'தயவுசெய்து சரியான மின்னஞ்சலை உள்ளிடுங்கள்.',
    'invalid_phone' => 'தயவுசெய்து சரியான தொலைபேசி எண்ணை உள்ளிடுங்கள்.',
    //updated
    
    'platform_title' => 'விமோசன அரங்கம்',
    'site_title' => 'விமோசன அரங்கம்',
    'nav_home' => 'முகப்பு',
    'nav_report' => 'அறிக்கை',
    'nav_volunteer' => 'தன்னார்வலர்',
    'nav_resource' => 'வளங்கள்',
    'nav_contact' => 'தொடர்பு கொள்ளவும்',

    'hero_title' => 'உங்கள் உதவி ஒரு வாழ்க்கையை காப்பாற்றலாம்',
    'hero_subtitle' => 'பாதிக்கப்பட்டவர்களுக்கு உதவுவதற்கு நாம் ஒன்றாக செயல்படலாம்',

    'disaster_awareness' => 'விபத்து விழிப்புணர்வு',

    'cyclone' => 'சுழற்காற்று',
    'cyclone_info' => 'சுழற்காற்றுகள் கடுமையான காற்றும் மழையும் கொண்டு வருகிறது. பாதுகாப்பான இடத்திற்கு சென்றிடுங்கள் மற்றும் அதிகாரிகளின் அறிவுரைகளை பின்பற்றுங்கள்.',

    'wildfire' => 'காட்டுத் தீ',
    'wildfire_info' => 'காட்டுத் தீ வேகமாக பரவுகிறது. புகை மற்றும் தீயை தவிர்க்கவும், பாதுகாப்பான இடத்திற்குச் செல்லவும்.',

    'flood' => 'வேளாண்மை வெள்ளம்',
    'flood_info' => 'வெள்ளம் தாழ்வான பகுதிகளை வேகமாக மூடக்கூடும். உயரமான இடங்களுக்குச் செல்லவும் மற்றும் பாதுகாப்பாக இருங்கள்.',

    'earthquake' => 'நிலநடுக்கம்',
    'earthquake_info' => 'நிலநடுக்கத்தின் போது சுவர் மற்றும் படிகளில் இருந்து விலகி தலையை பாதுகாக்கவும்.',

    'drought' => 'வறட்சி',
    'drought_info' => 'வறட்சி நீர்த்தட்டுப்பாட்டிற்கு வழிவகுக்கும். நீரை மிதமாகவும், சிக்கனமாகவும் பயன்படுத்துங்கள்.',

    'pandemic' => 'பரவலான நோய்கள்',
    'pandemic_info' => 'முகக்கவசங்களை அணியவும், கைசுத்தம் செய்யவும் மற்றும் சமூக இடைவெளியை கடைப்பிடிக்கவும்.',

    'footer_rights' => '© 2025 விமோசன அரங்கம். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    'footer_blog' => 'நிகழ்வுகள் மற்றும் செய்திகள்',


    // Main site strings
    'site_title' => 'ரிலீஃப் ஸ்பியர்',
    'alt_logo'                                 => 'ரிலீஃப் ஸ்பீயர் லோகோ',
    'relief_sphere'                            => 'ரிலீஃப் ஸ்பீயர்',
    'about_us'                                 => 'எங்களை பற்றி',
    'report_incident'                          => 'நிகழ்வை புகாரளிக்கவும்',
    'volunteer'                                => 'தன்னார்வலர்',
    'resource_collection'                      => 'வள சேகரிப்பு',
    'contact'                                  => 'தொடர்பு கொள்ள',
    'profile'                                  => 'சுயவிவரம்',
    'logout'                                   => 'வெளியேறு',
    'hero_title'                               => 'ரிலீஃப் ஸ்பீயருக்கு வரவேற்கிறோம்',
    'hero_subtitle'                            => 'உங்கள் நம்பகமான பேரழிவு உதவி கூட்டாளி',
    'key_features'                             => 'முக்கிய அம்சங்கள்',
    'feature_realtime_alerts_title'            => 'உண்மையிலேயே அறிவிப்புகள்',
    'feature_realtime_alerts_desc'             => 'பேரழிவுகள் பற்றிய அறிவிப்புகளை உடனடியாகப் பெறுங்கள்.',
    'feature_volunteer_system_title'            => 'தன்னார்வலர் அமைப்பு',
    'feature_volunteer_system_desc'             => 'அசௌகரியங்கள் நேரத்தில் உதவ எளிதாக இணையுங்கள்.',
    'feature_resource_coordination_title'       => 'வள ஒருங்கிணைப்பு',
    'feature_resource_coordination_desc'        => 'வளங்களை திறமையாக நிர்வகிக்கவும்.',
    'footer_resource_collection_title'           => 'வள சேகரிப்பு',
    'footer_resource_collection_desc'            => 'அத்தியாவசிய பொருட்களை சேகரித்து பகிருங்கள்.',
    'footer_volunteer_title'                      => 'தன்னார்வலர்',
    'footer_volunteer_desc'                       => 'தன்னார்வலராகி வேறுபாடு உருவாக்குங்கள்.',
    'footer_report_incident_title'                => 'நிகழ்வை புகாரளிக்கவும்',
    'footer_report_incident_desc'                 => 'உடனடியாக உதவி பெற நிகழ்வுகளை புகாரளிக்கவும்.',
    'blog'                                       => 'பிளாக்',

    // Login related strings
    'login_title'                              => 'பேரழிவு உதவிக்கு உள்நுழைக',
    'email_or_phone'                           => 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
    'password'                                 => 'கடவுச்சொல்',
    'login_btn'                                => 'உள்நுழை',
    'create_account'                           => 'கணக்கை உருவாக்கவும்',
    'no_account'                               => 'கணக்கு இல்லையா?',
    'invalid_password'                         => '❌ தவறான கடவுச்சொல்!',
    'email_not_found'                          => '❌ மின்னஞ்சல் அல்லது தொலைபேசி எண் காணப்படவில்லை!',
    'invalid_email'                            => 'தயவுசெய்து செல்லுபடியாகும் மின்னஞ்சல் வடிவத்தை உள்ளிடவும்.',
    'invalid_phone'                            => 'தயவுசெய்து செல்லுபடியாகும் தொலைபேசி எண்ணை உள்ளிடவும்.',
];
?>
